### ISSUE TITLE
[BUG] vscode-instant-markdown not launch when select markdown file

### ISSUE THREAD

**Issue by badmonster-nc** [dbankier/vscode-instant-markdown#4]
my configuration:
OS: xubuntu 16.10
Vscode : Version 1.8.0
               Commit 38746938a4ab94f2f57d9e1309c51fd6fb37553d
               Date 2016-12-13T18:03:00.506Z
               Shell 1.4.6
               Renderer 53.0.2785.143
               Node 6.5.0
instant markdown version: 0.2.1

When i select markdown file, preview not launch in my browser (google chrome).
In the console in vscode, i have this error:
"
[Extension Host] >>> /home/me/.vscode/extensions/dbankier.vscode-instant-markdown-0.2.1/node_modules/instant-markdown-d/node_modules/socket.io/lib/store.js:35
Store.prototype.__proto__ = EventEmitter.prototype;
                                        ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (/home/me/.vscode/extensions/dbankier.vscode-instant-markdown-0.2.1/node_modules/instant-markdown-d/node_modules/socket.io/lib/store.js:35:41)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/me/.vscode/extensions/dbankier.vscode-instant-markdown-0.2.1/node_modules/instant-markdown-d/node_modules/socket.io/lib/manager.js:16:13)
    at Module._compile (module.js:573:32)

extensionHost.ts:293 [Extension Host] !!> 1
"

**Comment by dbankier** [comment]
new release closes this
